defaults:
  - default_dataset

# torchrun --master_port=2200 --nproc_per_node=4 launch.py  --config default_object

exp_name: 0416_object_shuffle_query_head_v3
img_size: 518
num_workers: 0
seed_value: 30
accum_steps: 1    # We did not use gradient accumulation in our training, while if you suffer from OOM, you can try to use it.
patch_size: 14
val_epoch_freq: 10
max_img_per_gpu: 80

limit_train_batches: 160 # sample 幾次 (一次 per gpu / img num)
# limit_train_batches:  100
# limit_train_batches:  50
limit_val_batches: 35

debug:
  force_model_output_to_ground_truth: False

data:
  # The code for data still looks too complicated. I should refactor this again (do I have time?...)
  train:
    _target_: data.dynamic_dataloader.DynamicTorchDataset
    num_workers: ${num_workers}
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_size: ${img_size}
      patch_size: ${patch_size}
      debug: False
      map_xyz_bfloat16: False
      repeat_batch: False
      skip_process_batch: True
      img_nums: [4, 4]
    dataset:
      _target_: data.composed_dataset.ComposedDataset
      dataset_configs:
        - _target_: data.datasets.6d_pose_normalize.SixDPoseNormalizeDataset
          split: train
          DATA_ROOT: /dataset/0415_fixedCam_diffpose_25k_google
          OBJECT_IMAGE_ROOT: /dataset/object_space_renders_all
          selected_views: [1, 5, 10, 15]
          object_input_views: [1, 3, 8, 12]
          num_object_views: 4
          shuffle_selected_views: true
          load_point_map: false
          use_stride4_scale_estimate: false
          only_run_start: run_0000
          only_run_end: run_2000
  val:
    _target_: data.dynamic_dataloader.DynamicTorchDataset
    num_workers: ${num_workers}
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_size: ${img_size}
      patch_size: ${patch_size}
      debug: False
      map_xyz_bfloat16: False
      skip_process_batch: True
      img_nums: [4, 4]
    dataset:
      _target_: data.composed_dataset.ComposedDataset
      dataset_configs:
        - _target_: data.datasets.6d_pose_normalize.SixDPoseNormalizeDataset
          split: val
          DATA_ROOT: /dataset/0415_fixedCam_diffpose_25k_google
          OBJECT_IMAGE_ROOT: /dataset/object_space_renders_all
          selected_views: [1, 5, 10, 15]
          object_input_views: [1, 3, 8, 12]
          num_object_views: 4
          shuffle_selected_views: true
          load_point_map: false
          use_stride4_scale_estimate: false
          only_run_start: run_2001
          only_run_end: run_2499


logging:
  log_dir: logs/${exp_name}
  use_wandb: True
  log_visuals: False
  log_freq: 1
  log_level_primary: DEBUG
  log_level_secondary: WARNING
  all_ranks: False
  tensorboard_writer:
    _target_: train_utils.tb_writer.TensorBoardLogger
    path: ${logging.log_dir}/tensorboard
  wandb_writer:
    _target_: train_utils.wandb_logger.WandbLogger
    path: ${logging.log_dir}/wandb
    project: vggt-objectspc
    entity: null
    name: ${exp_name}
    mode: online
    resume: null
  scalar_keys_to_log:
    train:
      keys_to_log:
        - loss_objective
        # - loss_conf_object_point
        # - loss_reg_object_point
        # - loss_grad_object_point
        # - loss_object_mask
        # - loss_object_mask_bce
        # - loss_object_mask_dice
        - loss_object_srt
        - loss_object_pose
        - loss_object_translation
        # - loss_object_relative_pose
        # - loss_object_relative_pose_rot
        # - loss_object_relative_pose_translation
        # - loss_object_pose_init
    val:
      keys_to_log:
        - loss_objective
        # - loss_conf_object_point
        # - loss_reg_object_point
        # - loss_grad_object_point
        # - loss_object_mask
        # - loss_object_mask_bce
        # - loss_object_mask_dice
        - loss_object_srt
        - loss_object_pose
        - loss_object_translation
        # - loss_object_relative_pose
        # - loss_object_relative_pose_rot
        # - loss_object_relative_pose_translation
        # - loss_object_pose_init



checkpoint:
  save_dir: logs/${exp_name}/ckpts
  save_freq: 10
  resume_checkpoint_path: /omni_vggt/model/model.pt
  load_training_state: True
  load_scaler_state: True
  strict: False


loss:
  _target_: loss.MultitaskLoss
  camera: null
  depth: null
  point: null
  track: null
  # object_point:
  #   weight: 1.0
  #   gamma: 1.0
  #   alpha: 0.2
  #   gradient_loss_fn: "normal"
  #   valid_range: -1
  # object_mask:
  #   weight: 1.0
  #   bce_weight: 1.0
  #   dice_weight: 1.0
  #   pos_weight: 2.0
  object_srt:
    weight: 1.0
    use_iter_loss: True
    loss_type: l1
    gamma: 0.6
    weight_pose: 1.0
    weight_translation: 1.0
    # rotation_loss_type: geodesic
    # init_w: 1.0  # disabled because loss_object_pose_init is removed
  # object_relative_pose:
  #   weight: 1.0
  #   loss_type: l1
  #   rotation_loss_type: l1
  #   gamma: 0.6
  #   weight_pose: 1.0
  #   weight_translation: 1.0




optim:
  param_group_modifiers: False
  train_object_token_only: False
  keep_frozen_aggregator_train_mode: True

  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-4
    weight_decay: 0.05

  frozen_module_names:
      - "*aggregator*"

  amp:
    enabled: True
    amp_dtype: bfloat16
  gradient_clip:
    _target_: train_utils.gradient_clip.GradientClipper
    configs:
      # - module_name: ["shared_object_latent"]
      #   max_norm: 1.0
      #   norm_type: 2
      # - module_name: ["aggregator"]
      #   max_norm: 1.0   # feel free to reduce this if you see instabilities
      #   norm_type: 2
      # - module_name: ["pre_object_token_cross_attn"]
      #   max_norm: 1.0
      #   norm_type: 2
      - module_name: ["object_token_cross_attn", "object_token_cross_attn_blocks", "object_prototype_poolers"]
        max_norm: 1.0
        norm_type: 2
      # - module_name: ["object_pt_head"]
      #   max_norm: 1.0   # feel free to reduce this if you see instabilities
      #   norm_type: 2
      # - module_name: ["object_mask_head"]
      #   max_norm: 1.0
      #   norm_type: 2
      - module_name: ["object_srt_head"]
        max_norm: 1.0
        norm_type: 2
  options:
    lr:
      - scheduler:
          _target_: fvcore.common.param_scheduler.CompositeParamScheduler
          schedulers:
            - _target_: fvcore.common.param_scheduler.LinearParamScheduler
              start_value: 1e-6
              end_value: 2e-4
            - _target_: fvcore.common.param_scheduler.CosineParamScheduler
              start_value: 2e-4
              end_value: 1e-6
          lengths: [0.05, 0.95]
          interval_scaling: ['rescaled', 'rescaled']
    weight_decay:
      - scheduler:
          _target_: fvcore.common.param_scheduler.ConstantParamScheduler
          value: 0.05


max_epochs: 100

model:
  _target_: vggt.models.vggt.VGGT
  enable_camera: False
  enable_depth: False
  enable_point: False
  enable_track: False
  enable_object_point: False
  enable_object_mask: False
  enable_object_srt: True
  use_shared_object_latent: False # set False to switch back to the original version (no shared latent)
  enable_object_cross_attn: False
  enable_pre_aggregator_object_cross_attn: False
  enable_multi_layer_object_prototype_cross_attn: True
  enable_global_pool_scene_object_pose_head: False  # when True, scene/object are pooled independently, concatenated, then fed to the original transformer decoder pose head
  concat_first_camera_token_to_object_pose_head: False
  enable_camera_style_object_pose_head: False
  enable_query_style_object_pose_head: True
  object_prototype_layer_indices: [4, 11, 17, 23]
  object_prototype_num_tokens: 32
  object_prototype_object_encoder_no_grad: False
  object_cross_attn_heads: 16
  # object_pose_cfg:
  #   ief_iters: 4
  #   pose_encoding_type: absT_quaR
  #   object_trunk_depth: 4
  #   object_num_heads: 16
  #   object_mlp_ratio: 4
  #   object_init_values: 0.01
  #   trans_act: linear
  #   quat_act: linear


distributed:
  # check https://docs.pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html for options
  backend: nccl
  comms_dtype: None
  find_unused_parameters: False
  timeout_mins: 30
  gradient_as_bucket_view: True  # Less memory used
  bucket_cap_mb: 25
  broadcast_buffers: True

cuda:
    cudnn_deterministic: False
    cudnn_benchmark: False
    allow_tf32: True
